dist: trusty
before_install:
  - sudo apt-get install -y ninja-build
script:
  - bash -x test.sh
  - bash -x build.sh
  - echo "Default variant END"
  - rm Firmware/Configuration_prusa.h
  - cp Firmware/variants/1_75mm_MK25-RAMBo13a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh
  - echo "1_75mm_MK25-RAMBo13a-E3Dv6full variant END"
  - rm Firmware/Configuration_prusa.h
  - cp Firmware/variants/1_75mm_MK25-RAMBo10a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh
  - echo "1_75mm_MK25-RAMBo10a-E3Dv6full variant END"
  - rm Firmware/Configuration_prusa.h
  - cp Firmware/variants/1_75mm_MK2-RAMBo13a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh
  - echo "1_75mm_MK2-RAMBo13a-E3Dv6full variant END"
  - rm Firmware/Configuration_prusa.h
  - cp Firmware/variants/1_75mm_MK2-RAMBo10a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh
  - echo "1_75mm_MK2-RAMBo10a-E3Dv6full variant END"